### ISSUE TITLE
Checklist for publishing

### ISSUE THREAD

**Issue by KRiedmiller** [graeter-group/kimmdy#172]
# Things to change while making KIMMDY 2.0 public

* [x] `setup.cfg`: [options.extras_require] should not point to git repo, but pip package instead
* [x] `tox.ini`: deps should not contain `-r requirements` but `extras = plugins`
* [x] documentation hosted at gh pages or hits servers
* [ ] version number reset
* [x] check installation precedure, incl subpackages, plugins, etc.
* [x] yaml scheme online?
* [x] Branch protection for main
* [ ] citations
